title: Lorena Garcia
logo: "img/photo.jpg?raw=true"
description: 
  Data Analyst
  <br><br>
  <a href="https://www.linkedin.com/in/alorenagc/">View my profile on LinkedIn</a>

remote_theme: pages-themes/merlot@v0.2.0
